// terrainBuilder.js — Splat cloud, ocean floor mesh, contour shader, country borders
import * as THREE from 'three';
import {
    MAP_WIDTH, MAP_HEIGHT, MAX_SPLAT_BUDGET, prng,
    SPLAT_BRIGHTNESS, SPLAT_LAND_LIFT, SPLAT_LAND_GAMMA, SPLAT_SATURATION, SPLAT_HEMI_STRENGTH, SPLAT_BIOME_STRENGTH,
    SPLAT_LAND_GRID, SPLAT_OCEAN_GRID,
    SPLAT_FADE_START, SPLAT_FADE_END,
    AQUARIUM_DEPTH,
    DAYNIGHT_TERRAIN,
    SPLAT_FX,
    TERRAIN_VSCALE_LAND, TERRAIN_VSCALE_OCEAN,
} from './config.js';
import { quality } from './qualityManager.js';

// Module-level references set once via init
let _demData, _imgW, _imgH, _colorData, _colorW, _colorH;
let _gebcoData, _gebcoW, _gebcoH;
let _splatCloud = null;

export function initTerrainData({ demData, imgW, imgH, colorData, colorW, colorH,
                                   gebcoData, gebcoW, gebcoH }) {
    _demData   = demData;
    _imgW      = imgW;
    _imgH      = imgH;
    _colorData = colorData;
    _colorW    = colorW;
    _colorH    = colorH;
    _gebcoData = gebcoData || null;
    _gebcoW    = gebcoW    || 0;
    _gebcoH    = gebcoH    || 0;
    if (_gebcoData) {
        console.log(`[GEBCO] Loaded ${_gebcoW}×${_gebcoH} bathymetry heightmap.`);
    }
}

export function getTrueElevation(x, z) {
    let u = Math.floor((x / MAP_WIDTH  + 0.5) * (_imgW - 1));
    let v = Math.floor((z / MAP_HEIGHT + 0.5) * (_imgH - 1));
    u = Math.max(0, Math.min(u, _imgW - 1));
    v = Math.max(0, Math.min(v, _imgH - 1));
    const idx = (v * _imgW + u) * 4;
    return (_demData[idx] * 256.0 + _demData[idx + 1] + _demData[idx + 2] / 256.0) - 32768.0;
}

// GEBCO elevation — same Terrarium decode, reads from the GEBCO PNG.
// Only valid for ocean pixels; do not use for land.
export function getGEBCOElevation(x, z) {
    let u = Math.floor((x / MAP_WIDTH  + 0.5) * (_gebcoW - 1));
    let v = Math.floor((z / MAP_HEIGHT + 0.5) * (_gebcoH - 1));
    u = Math.max(0, Math.min(u, _gebcoW - 1));
    v = Math.max(0, Math.min(v, _gebcoH - 1));
    const idx = (v * _gebcoW + u) * 4;
    return (_gebcoData[idx] * 256.0 + _gebcoData[idx + 1] + _gebcoData[idx + 2] / 256.0) - 32768.0;
}

// Best available elevation at (x, z):
//   Ocean pixels  → GEBCO (450 m resolution, authoritative bathymetry)
//   Land  pixels  → Terrarium (satellite imagery compensates for coarser DEM)
//   GEBCO missing → falls back to Terrarium for both
export function getBestElevation(x, z) {
    const terrariumH = getTrueElevation(x, z);
    if (_gebcoData && terrariumH < 0) {
        return getGEBCOElevation(x, z);
    }
    return terrariumH;
}

// Sample satellite colour at any scene-space (x, z) coordinate.
// Returns { r, g, b } in 0–1 range.  Used by city terrain patches to produce
// mesh terrain that colour-matches the surrounding point cloud.
export function getTrueColor(x, z) {
    if (!_colorData) return { r: 0.45, g: 0.45, b: 0.45 };
    let u = Math.floor((x / MAP_WIDTH  + 0.5) * (_colorW - 1));
    let v = Math.floor((z / MAP_HEIGHT + 0.5) * (_colorH - 1));
    u = Math.max(0, Math.min(u, _colorW - 1));
    v = Math.max(0, Math.min(v, _colorH - 1));
    const idx = (v * _colorW + u) * 4;
    return {
        r: _colorData[idx]     / 255,
        g: _colorData[idx + 1] / 255,
        b: _colorData[idx + 2] / 255,
    };
}

// ── Normal map loader ─────────────────────────────────────────────────────────
// Loads terrain_normals.png (generated by tools/generate_normals.py) as a
// Three.js texture for use by the continent mesh and city terrain patches.
// Returns null gracefully if the file is absent so terrain still renders
// without normals — no hard dependency on the preprocessing step.
export function loadNormalMap(url = './terrain_normals.png') {
    return new Promise((resolve) => {
        const loader = new THREE.TextureLoader();
        loader.load(
            url,
            (tex) => {
                // Normal maps must NOT be colour-managed — they encode directions,
                // not colours, so sRGB gamma correction would corrupt the normals.
                tex.colorSpace   = THREE.NoColorSpace;
                tex.wrapS        = THREE.RepeatWrapping;
                tex.wrapT        = THREE.RepeatWrapping;
                tex.generateMipmaps = true;
                tex.minFilter    = THREE.LinearMipmapLinearFilter;
                tex.magFilter    = THREE.LinearFilter;
                tex.anisotropy   = 16;  // max sharpness at grazing angles — upgraded from 4
                console.log('[NormalMap] Loaded terrain_normals.png');
                resolve(tex);
            },
            undefined,
            (err) => {
                console.warn(
                    '[NormalMap] terrain_normals.png not found — ' +
                    'run tools/generate_normals.py to enable high-res normals.'
                );
                resolve(null);  // graceful degradation
            }
        );
    });
}

export function createHighFidelityPointCloud(scene) {
    // Stand up the geometry and ShaderMaterial immediately so the scene
    // object exists at startup — the worker fills in the buffers async.
    const geo = new THREE.BufferGeometry();

    // ── Lit Point Cloud Shader ────────────────────────────────────────────────
    // Each splat carries a pre-computed surface normal (terrainWorker.js builds
    // it via central differences on the height field).  The fragment stage
    // applies Lambertian (dot(normal, sunDir)) diffuse + a constant ambient
    // floor, plus a warm dawn tint on sun-facing faces.
    //
    // Result: mountain ranges cast natural shadows as the sun tracks across
    // the sky — north faces dark, south faces bright, twilight flanks amber.
    const mat = new THREE.ShaderMaterial({
        uniforms: {
            uSunDir:        { value: new THREE.Vector3(0, 1, 0) },  // unit sun vector
            uSunElevation:  { value: 1.0 },                         // -1..1
            uRadianceMap:   { value: null },   // terrain_radiance_baked.png — set by main.js
            uUseRadiance:   { value: 0.0 },    // 0 = runtime Sobel, 1 = MeshLab bake
            // Phase 3 — AO shadow tint. Default is deep indigo; tune from console:
            //   window.splatCloud.material.uniforms.uAOTint.value.set(r,g,b)
            uAOTint:        { value: new THREE.Color(0.08, 0.04, 0.22) },
            // Land-only brightness multiplier (ocean stays untouched).
            // Tune live: window.splatCloud.material.uniforms.uBrightness.value = X
            uBrightness:    { value: SPLAT_BRIGHTNESS },
            // Additive land lift — pulls near-black terrain out of the shadows.
            uLandLift:      { value: SPLAT_LAND_LIFT },
            // Land gamma — values < 1.0 lift shadows aggressively (like Curves in Photoshop).
            // 1.0 = no effect, 0.65 = good shadow lift.
            uLandGamma:     { value: SPLAT_LAND_GAMMA },
            // Saturation multiplier — >1 makes colours more vivid, 1.0 = no change.
            // Tune: window.splatCloud.material.uniforms.uSaturation.value = 1.5
            uSaturation:    { value: SPLAT_SATURATION },
            uFade:          { value: 1.0 },  // crossfade LOD: 1=fully visible, 0=invisible
            uTilt:          { value: 0.0 },  // 0=top-down, 1=horizontal — drives oblique brightness boost
            // ── Hemisphere lighting — slope-direction dependent fill ──────────
            // uHemiStrength: 0=off (flat AMBIENT), 1=full hemisphere effect.
            // Tune live: window.splatCloud.material.uniforms.uHemiStrength.value = 0.5
            uHemiStrength:   { value: SPLAT_HEMI_STRENGTH },
            // Sky fill color — cool blue received by upward-facing slopes
            uHemiSkyColor:   { value: new THREE.Color(0.52, 0.62, 0.78) },
            // Ground bounce color — warm neutral received by downward-facing slopes
            uHemiGroundColor:{ value: new THREE.Color(0.28, 0.22, 0.18) },
            // ── Biome tinting — latitude & elevation based color zoning ──────
            // uBiomeStrength: 0=off, 1=full. Tune live:
            //   window.splatCloud.material.uniforms.uBiomeStrength.value = 0.5
            uBiomeStrength: { value: SPLAT_BIOME_STRENGTH },
            uPolarTint:     { value: new THREE.Color(0.78, 0.85, 0.95) },  // cool ice-blue
            uAridTint:      { value: new THREE.Color(0.92, 0.82, 0.60) },  // warm amber desert
            uSnowTint:      { value: new THREE.Color(0.90, 0.90, 0.92) },  // gray-white snowcap
            // ── Map-edge fade ────────────────────────────────────────────────
            // Points within (uEdgeFadeStart..MAP_HALF) of any boundary fade
            // their alpha down so the world dissolves into the void instead
            // of cliffing off. Tune live:
            //   window.splatCloud.material.uniforms.uEdgeFadeStart.value = 110
            uEdgeFadeStart: { value: 125.0 },   // start fading at this |x| or |z|
            uEdgeFadeEnd:   { value: 150.0 },   // fully transparent at the boundary
            // ── Day/night terrain shading — geographic terminator ────────────
            // Sub-solar point (radians) written each frame by main.js from
            // skyManager (same site that writes uSunDir). Tune live:
            //   window.splatCloud.material.uniforms.uNightDim.value = 0.8
            uSubSolarLat:   { value: 0.0 },
            uSubSolarLon:   { value: 0.0 },
            uNightDim:      { value: DAYNIGHT_TERRAIN.STRENGTH },
            uNightFloor:    { value: DAYNIGHT_TERRAIN.FLOOR },
            // ── Splat FX — coverage scale + animated ridge energy ────────────
            uSplatScale:    { value: SPLAT_FX.SCALE },
            uTime:          { value: 0.0 },   // seconds, written by main.js loop
            uRidgePulse:    { value: SPLAT_FX.RIDGE_PULSE },
            // Vertical exaggeration — used to decode metres from vHeight for
            // contours and cliff thresholds. Set once; never written at runtime.
            uVScaleLand:    { value: TERRAIN_VSCALE_LAND },
            uVScaleOcean:   { value: TERRAIN_VSCALE_OCEAN },
        },
        vertexColors: true,
        vertexShader: /* glsl */`
            attribute float aSize;
            attribute float aHeight;
            attribute vec3  aNormal;
            attribute float aRidge;

            uniform sampler2D uRadianceMap;
            uniform float     uUseRadiance;

            varying vec3  vColor;
            varying vec3  vWorldNormal;
            varying float vHeight;
            varying float vRidge;
            varying float vDist;
            varying float vLatitude;  // 0=equator, 1=pole — abs(Z)/150
            varying float vEdgeFade;  // 1=interior, 0=at map boundary
            varying float vDayFactor; // 1=full day, 0=full night (geographic terminator)

            uniform float uEdgeFadeStart;
            uniform float uEdgeFadeEnd;
            uniform float uSubSolarLat;  // radians
            uniform float uSubSolarLon;  // radians
            uniform float uSplatScale;   // global point-size multiplier

            void main() {
                vColor       = color;
                vHeight      = aHeight;

                // ── Geographic day/night factor ────────────────────────────────
                // Recover lon/lat from scene XZ (inverse Mercator, mirrors
                // lonLatToScene in aisManager.js), then compute local solar
                // elevation against the sub-solar point. Smooth twilight band.
                float lonRad = position.x * (3.14159265 / 150.0);          // x → lon
                float mercY  = -position.z * (3.14159265 / 150.0);         // z → mercator y
                float latRad = 2.0 * atan(exp(mercY)) - 1.57079633;        // → lat
                float sinElev = sin(latRad) * sin(uSubSolarLat)
                              + cos(latRad) * cos(uSubSolarLat) * cos(lonRad - uSubSolarLon);
                vDayFactor = smoothstep(-0.10, 0.14, sinElev);
                // Latitude: Z axis spans -150(north) to +150(south), 150 = MAP_HEIGHT/2
                vLatitude    = abs(position.z) / 150.0;

                // ── Ridge glow source — baked MeshLab map or runtime Sobel ─────
                // UV maps scene XZ to [0,1]: u = x/300+0.5, v = z/300+0.5
                // The baked radiance map encodes curvature from the Poisson mesh,
                // which captures real ridge geometry rather than a DEM gradient.
                vec2  terrainUV   = vec2(position.x / 300.0 + 0.5,
                                         position.z / 300.0 + 0.5);
                float bakedRidge  = texture2D(uRadianceMap, terrainUV).r;
                vRidge = mix(aRidge, bakedRidge, uUseRadiance);

                // Transform normal to world space — no non-uniform scale so
                // mat3(modelMatrix) is equivalent to the normal matrix here.
                vWorldNormal = normalize(mat3(modelMatrix) * aNormal);

                vec4  mvPos  = modelViewMatrix * vec4(position, 1.0);
                float dist   = length(mvPos.xyz);
                vDist        = dist;

                // ── Map-edge alpha fade ────────────────────────────────────────
                // smoothstep(uEdgeFadeEnd, uEdgeFadeStart, d) = 1 when d <= start,
                // 0 when d >= end. We take max(|x|,|z|) so corners fade fastest.
                float edgeD  = max(abs(position.x), abs(position.z));
                vEdgeFade    = smoothstep(uEdgeFadeEnd, uEdgeFadeStart, edgeD);

                // ── LOD size scaling ──────────────────────────────────────────
                // Base: perspective-correct sizing — points shrink with distance.
                // LOD layer: distant splats get a minimum pixel floor so they
                // maintain surface coverage even when the perspective size drops
                // below 1 px.  Close-up splats stay small and crisp; far splats
                // stay at least 1.5 px so no gaps appear at low zoom.
                // The Gaussian falloff in the fragment stage makes the larger
                // distant splats soft rather than blocky.
                // Raised multiplier 350→500 so splats are larger at all distances.
                // Raised lodMin floor 0.4/1.2→2.0/2.5 so every splat is at least
                // 2 px wide — fills the gaps visible at oblique close zoom where
                // mid-distance splats were shrinking below coverage threshold.
                float perspSize = aSize * (500.0 / max(dist, 1.0));
                float lodMin    = mix(1.5, 2.0, clamp(dist / 300.0, 0.0, 1.0));
                // Adaptive cap — close zoom gets larger dots for surface coverage,
                // medium/far zoom stays tight and crisp.
                // Raised from 3.0 to 4.5 so splats overlap more at close zoom and
                // read as a continuous surface instead of discrete grainy dots.
                float maxSize   = mix(4.5, 3.0, clamp(1.0 - dist / 80.0, 0.0, 1.0));
                // uSplatScale: global coverage multiplier — >1 closes the gaps
                // between points so terrain reads as continuous surface.
                gl_PointSize    = clamp(perspSize, lodMin, maxSize) * uSplatScale;
                gl_Position  = projectionMatrix * mvPos;
            }
        `,
        fragmentShader: /* glsl */`
            uniform vec3  uSunDir;
            uniform float uSunElevation;
            uniform vec3  uAOTint;
            uniform float uBrightness;
            uniform float uLandLift;
            uniform float uLandGamma;
            uniform float uSaturation;
            uniform float uFade;
            uniform float uTilt;
            uniform float uHemiStrength;
            uniform vec3  uHemiSkyColor;
            uniform vec3  uHemiGroundColor;
            uniform float uBiomeStrength;
            uniform vec3  uPolarTint;
            uniform vec3  uAridTint;
            uniform vec3  uSnowTint;
            uniform float uNightDim;
            uniform float uNightFloor;
            uniform float uTime;
            uniform float uRidgePulse;
            uniform float uVScaleLand;
            uniform float uVScaleOcean;

            varying vec3  vColor;
            varying vec3  vWorldNormal;
            varying float vHeight;
            varying float vRidge;
            varying float vDist;
            varying float vLatitude;
            varying float vEdgeFade;
            varying float vDayFactor;

            void main() {
                // ── Gaussian soft splat ───────────────────────────────────────
                // Replace hard disc clip with a smooth exponential falloff.
                // Adjacent splats now blend into each other → continuous surface
                // appearance even at moderate density; crisp edges on ridges
                // because those splats are small (aSize ≈ 0.12).
                vec2  cxy      = gl_PointCoord - 0.5;
                float r2       = dot(cxy, cxy);
                // Wider visible radius (0.06 → 0.11) + softer Gaussian (8.0 → 5.0).
                // Each splat covers more of its quad and fades more gradually,
                // so adjacent splats overlap and blur into each other instead of
                // showing as discrete granular dots.
                if (r2 > 0.11) discard;
                float softAlpha = exp(-r2 * 5.0);

                // ── Lambertian diffuse — DISABLED ─────────────────────────────
                // Sun-direction lighting removed. The user's intent is to see
                // the splat's baked satellite-derived colours directly, not a
                // slope-shaded "lit" version of them. NdotL forced to zero so
                // the directional sun effect is dead while uSunDir + dayAmt
                // remain available for other consumers (water shader still
                // uses them; day/night UI still drives sun-elevation logic).
                float NdotL   = 0.0;

                // ── Non-directional ambient occlusion ─────────────────────────
                // Slope darkening without any sun direction — purely a function
                // of how upward-facing the surface normal is. Flat/peak surfaces
                // (normal.y near 1.0) stay at full brightness; steep cliff faces
                // (normal.y near 0) darken by up to 30%. Creates dimensional
                // shading on mountains so the Himalayas, Andes, Rockies read
                // as terrain, not as flat painted texture. Ocean-masked so it
                // applies only to land — ocean keeps its bathymetric flat look.
                float aoFactor = 0.70 + 0.30 * max(vWorldNormal.y, 0.0);

                float dayAmt  = clamp(uSunElevation * 2.0 + 0.3, 0.0, 1.0);

                // ── Hemisphere ambient — sky fill + ground bounce ──────────
                // N.y = +1 → face points up  → full sky fill (cool blue)
                // N.y = -1 → face points down → ground bounce (warm brown)
                // mix(1.20, 2.00, hemiBlend) keeps mean at 1.60 — same overall
                // brightness as before, but distributed by slope direction.
                // uHemiStrength = 0 → falls back to flat AMBIENT 1.60 exactly.
                float hemiBlend  = vWorldNormal.y * 0.5 + 0.5;
                vec3  hemiColor  = mix(uHemiGroundColor, uHemiSkyColor, hemiBlend);
                float hemiAmbient = 1.20 + hemiBlend * 0.80;
                float AMBIENT = mix(1.60, hemiAmbient, uHemiStrength) + uTilt * 0.50;
                const float DIFFUSE = 0.62;

                float oceanMask = step(0.0, vHeight);   // 1 = land, 0 = ocean
                // Ocean brightness reduced to 0.68 to contrast against bright land.
                // Land stays at full AMBIENT+DIFFUSE calculation; ocean gets a fixed
                // darker floor so the blue depth palette reads as deep water.
                float lit = AMBIENT + NdotL * DIFFUSE * dayAmt;
                lit = mix(0.68, lit, oceanMask);

                vec3 litColor = vColor * lit;

                // Apply the non-directional AO factor — land only.
                litColor *= mix(1.0, aoFactor, oceanMask);

                // ── Hemisphere color tint ─────────────────────────────────────
                // Multiply a subtle sky/ground tint into land faces based on
                // slope direction. North-facing slopes go slightly cool-blue;
                // south-facing and hilltops stay neutral. Ocean excluded.
                litColor *= mix(vec3(1.0), hemiColor * 1.30, uHemiStrength * 0.40 * oceanMask);

                // ── Dawn / dusk warm tint — disabled to prevent gold coastal bleed.
                // The dawnAmt factor combined with high-vRidge coastal splats was
                // a secondary source of the warm coastline glow.  Set weight to 0.
                float dawnAmt = pow(max(0.0, 1.0 - abs(uSunElevation) * 3.0), 2.0);
                litColor = mix(litColor,
                               litColor * vec3(1.25, 1.02, 0.80),
                               dawnAmt * NdotL * dayAmt * 0.0 * oceanMask);

                // ── Topographic iso-contours (land only) ──────────────────────
                // Recover elevation in metres from the scene-space Y value.
                //   land:  finalY = hMeters / 1000  →  elevMeters = vHeight * 1000
                //   ocean: finalY = hMeters / 600   (contours suppressed by oceanMask)
                // Each splat is a point with one elevation, so contours appear as
                // statistically dense dots clustering along level lines — exactly
                // the dotted-line look of a topographic / tactical map.
                float elevMeters = vHeight * mix(600.0, 650.0, oceanMask) / mix(uVScaleOcean, uVScaleLand, oceanMask);

                // Minor ring every 500 m — muted teal glow
                float minorMod  = mod(abs(elevMeters), 500.0);
                float minorEdge = min(minorMod, 500.0 - minorMod);
                float isMinor   = (1.0 - smoothstep(0.0, 28.0, minorEdge)) * oceanMask;

                // Major ring every 2 500 m — warm amber tactical line
                float majorMod  = mod(abs(elevMeters), 2500.0);
                float majorEdge = min(majorMod, 2500.0 - majorMod);
                float isMajor   = (1.0 - smoothstep(0.0, 42.0, majorEdge)) * oceanMask;

                // Topo contours are cartographic reference — blend weight reduced
                // (0.55/0.80 → 0.28/0.48) so they read as map texture, not data tracks.
                litColor = mix(litColor, litColor * 0.4 + vec3(0.05, 0.70, 0.90) * 0.9,  isMinor * 0.28);
                litColor = mix(litColor, litColor * 0.2 + vec3(1.00, 0.52, 0.08) * 1.2,  isMajor * 0.48);

                // ── Normal-based ridge / edge glow ────────────────────────────
                // vRidge = terrain steepness 0–1 (computed in terrainWorker from
                // the gradient magnitude).  Steep ridges and canyon walls get a
                // subtle cyan accent.  Elevation gate (vHeight > 0.08 ≈ 80 m in
                // scene units) prevents the DEM's vertical cliff at the land→sea
                // boundary from triggering this — that cliff has near-zero elevation
                // but maximum vRidge, which was causing the golden coastline glow.
                float ridgePow      = pow(vRidge, 2.0);
                float ridgeElevGate = step(0.08, vHeight);        // 0 below 80 m, 1 above
                litColor = mix(litColor,
                               litColor + vec3(0.10, 0.55, 0.90) * 0.30,
                               ridgePow * 0.18 * oceanMask * ridgeElevGate);

                // ── AO violet shadow tint — REALLY disabled now ───────────────
                // Previous code's comments said "disabled" but multiplier was
                // 0.6, applying violet to all sun-away slopes. With NdotL=0
                // shadowFactor was = 1.0 and would have purpled the whole
                // world. Mix weight zeroed out properly.
                litColor = mix(litColor, litColor, 0.0);

                // ── Coastline accent ──────────────────────────────────────────
                // Was: a violet darkening shadow near the waterline (made
                // coastlines look bruised). Now: a subtle cyan brightening
                // edge at the land-side of the shoreline, so coastlines POP
                // against the new bathymetric ocean instead of being darkened
                // into it. Same coastProx falloff, opposite color logic.
                float coastProx = (1.0 - smoothstep(0.0, 0.020, vHeight)) * oceanMask;
                vec3 coastAccent = vec3(0.35, 0.85, 1.00);  // cool cyan-white
                litColor = mix(litColor,
                               litColor * 0.95 + coastAccent * 0.25,
                               coastProx * 0.55);

                // ── Land-only brightness lift — ocean stays untouched. ────────
                // Two-part approach:
                //   1. Multiplicative: scales colours that already have some value.
                //   2. Additive lift: pulls near-black land out of the shadows
                //      (multiplicative alone does nothing when vColor ≈ black).
                // Both are masked to oceanMask so the ocean is completely unaffected.
                // ── Land shadow lift — three-stage, ocean completely untouched ──
                // 1. Gamma curve: lifts near-black shadows aggressively (like Curves).
                //    pow(x, 0.65) turns 0.03 → 0.08, 0.1 → 0.16, 0.5 → 0.41.
                // 2. Multiplicative: scales the result up.
                // 3. Additive floor: absolute minimum brightness for darkest pixels.
                vec3 landColor  = pow(max(litColor, vec3(0.0)), vec3(uLandGamma));
                landColor      *= uBrightness;
                landColor       = max(landColor, vec3(0.10));   // dark floor
                // Adaptive ceiling — normal terrain stays at 0.97 (vivid),
                // but bright lit pixels (ice / polar snow) slide down to 0.68
                // so Antarctica doesn't blow out under ambient 1.50.
                // Transition: rawLum 0.80 (normal land) → 1.20 (bright ice).
                float iceRawLum = dot(litColor, vec3(0.299, 0.587, 0.114));
                float adaptCeil = mix(0.97, 0.68,
                                      clamp((iceRawLum - 0.80) / 0.40, 0.0, 1.0));
                landColor       = min(landColor, vec3(adaptCeil));
                // Saturation boost — mix away from luminance to restore vibrancy
                // lost during the gamma lift (which pushes colours toward grey).
                float landLum   = dot(landColor, vec3(0.299, 0.587, 0.114));
                landColor       = mix(vec3(landLum), landColor, uSaturation);
                // Distance-aware lift applied AFTER saturation so it can't be undone.
                // Full effect at close zoom, fades to zero by dist=150 — wide view untouched.
                float closeLift = uLandLift * clamp(1.0 - vDist / 150.0, 0.0, 1.0);
                landColor      *= (1.0 + closeLift);  // multiplicative — preserves hue
                landColor       = clamp(landColor, 0.0, 1.0);
                litColor = mix(litColor, landColor, oceanMask);

                // ── Emissive self-glow (steps 1–3) ───────────────────────────
                // Step 1: shadow factor — how dark is this face relative to sun
                // Step 2: tilt gate — scales with camera obliqueness; near zero
                //         when top-down so bright side is left alone
                // Step 3: blowout guard — suppresses emissive on already-bright
                //         pixels so lit faces don't blow out
                float shadowAmt    = 1.0 - clamp(NdotL * dayAmt, 0.0, 1.0);
                float emissiveGate = shadowAmt * (0.5 + uTilt * 0.5);
                float curLum       = dot(litColor, vec3(0.299, 0.587, 0.114));
                float blowoutGuard = clamp(1.0 - curLum * 2.0, 0.0, 1.0);
                vec3  emissive     = vColor * emissiveGate * blowoutGuard * 0.10;
                litColor          += emissive * oceanMask;

                // ── Coastal cliff suppression — MUST be after brightness lift ──
                // The lift's +0.16 additive floor undoes any pre-lift darkening.
                // Applying suppression here means the floor can't rescue cliff pixels.
                // vHeight = hMeters/1000 for land → 0.20 = 200 m scene units.
                // vRidge 0–1 steepness; coastal cliffs score ≈ 1.0.
                float pcCliff = smoothstep(0.28, 0.68, vRidge)
                              * (1.0 - smoothstep(0.0, 0.35 * uVScaleLand, vHeight))
                              * oceanMask;
                litColor  *= 1.0 - pcCliff * 0.97;
                // Dissolve steep coastal splats to transparent so they don't
                // leave a coloured dot outline ringing every coastline.
                softAlpha *= 1.0 - pcCliff * 0.95;

                // ── Biome tinting — latitude & elevation color zoning ─────────
                // Three independent masks applied as smooth gradient blends.
                // All applied to land only (oceanMask). Controlled by uBiomeStrength.
                // Convert scene-unit height to approximate metres for thresholds.
                float elevM = vHeight * 620.0;

                // 1) Polar mask: high-latitude ice/tundra desaturation (>~65°)
                float polarMask = smoothstep(0.64, 0.80, vLatitude);
                // Suppress polar tint at high elevation — mountains have own look
                polarMask *= 1.0 - smoothstep(500.0, 2500.0, elevM);
                polarMask  = clamp(polarMask * oceanMask, 0.0, 1.0);

                // 2) Arid mask: subtropical desert warmth (16°–32° bands)
                float aridDist = abs(vLatitude - 0.265) / 0.095;  // centred ~24°
                float aridMask = 1.0 - smoothstep(0.0, 1.4, aridDist);
                // Only low-elevation terrain — no desert above 2000m
                aridMask *= 1.0 - smoothstep(800.0, 2000.0, elevM);
                // Suppress where green channel dominates (equatorial forest)
                float greenDom = litColor.g - max(litColor.r, litColor.b);
                aridMask *= 1.0 - smoothstep(0.0, 0.08, greenDom);
                aridMask  = clamp(aridMask * oceanMask, 0.0, 1.0);

                // 3) Snow/rock mask: high-altitude gray-out (>3000m → 5500m full)
                float snowMask = smoothstep(3000.0, 5500.0, elevM);
                snowMask = clamp(snowMask * oceanMask, 0.0, 1.0);

                // Apply: luminance-preserving tint blend per biome
                float biomeLum  = dot(litColor, vec3(0.299, 0.587, 0.114));
                vec3 polarResult = mix(litColor,  uPolarTint * biomeLum * 1.6,  polarMask * 0.65);
                vec3 aridResult  = mix(polarResult, mix(polarResult, uAridTint * biomeLum * 1.5, 0.45), aridMask);
                vec3 snowResult  = mix(aridResult,  uSnowTint  * biomeLum * 1.4,  snowMask * 0.75);
                litColor = mix(litColor, snowResult, uBiomeStrength);
                litColor = clamp(litColor, 0.0, 1.0);

                // ── Ridge energy pulse — slow luminous flow along mountain ranges
                // Uses the existing ridge mask (vRidge); phase varies with height
                // and latitude so the glow travels along ranges instead of
                // blinking uniformly. uRidgePulse=0 disables. Additive color is
                // capped well below bloom threshold (0.95) — no bloom risk.
                float ridgeWave = 0.5 + 0.5 * sin(uTime * 0.6 + vHeight * 4.0 + vLatitude * 14.0);
                litColor += vec3(0.10, 0.34, 0.52) * vRidge * ridgeWave * uRidgePulse;
                litColor = clamp(litColor, 0.0, 1.0);

                // ── Day/night terminator dim ──────────────────────────────────
                // Night side of the terrain darkens toward uNightFloor; twilight
                // gets a faint warm tint so the terminator band reads naturally.
                // uNightDim=0 disables entirely (identical to pre-feature look).
                float dnFactor = mix(uNightFloor, 1.0, vDayFactor);
                vec3  dnColor  = litColor * dnFactor;
                float twilight = vDayFactor * (1.0 - vDayFactor) * 4.0;  // peaks at terminator
                dnColor += vec3(0.030, 0.012, 0.0) * twilight;            // subtle amber band
                litColor = mix(litColor, dnColor, uNightDim);

                gl_FragColor = vec4(litColor, softAlpha * uFade * vEdgeFade);
            }
        `,
        // Transparent required for Gaussian softAlpha — NormalBlending means
        // splats layer correctly without the additive blow-out on bright colours.
        transparent: true,
        depthWrite:  true,
        blending:    THREE.NormalBlending,
    });

    const splatCloud = new THREE.Points(geo, mat);
    splatCloud.name  = 'highFidelityPointCloud';
    _splatCloud      = splatCloud;
    scene.add(splatCloud);

    // Offload all heavy per-point math to a worker — keeps main thread free
    // during the rest of the init sequence.
    const worker = new Worker(new URL('./terrainWorker.js', import.meta.url), { type: 'module' });

    worker.onmessage = (e) => {
        const { positions, colors, sizes, heights, normals, ridges, count } = e.data;
        geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
        geo.setAttribute('color',    new THREE.BufferAttribute(colors,    3));
        geo.setAttribute('aSize',    new THREE.BufferAttribute(sizes,     1));
        geo.setAttribute('aHeight',  new THREE.BufferAttribute(heights,   1));
        geo.setAttribute('aNormal',  new THREE.BufferAttribute(normals,   3));
        geo.setAttribute('aRidge',   new THREE.BufferAttribute(ridges,    1));
        geo.computeBoundingSphere();
        const el = document.getElementById('node-count');
        if (el) el.innerText = count.toLocaleString();
        console.log(`[Terrain Worker] Built ${count.toLocaleString()} splats`);
        worker.terminate();
    };

    worker.onerror = (err) => {
        console.error('[Terrain Worker] failed:', err.message);
        worker.terminate();
    };

    // Structured-clone the DEM/colour data into the worker.
    // We can't transfer these buffers because getTrueElevation(),
    // createSolidOceanFloor(), and createCountryBorders() all need them
    // on the main thread after this call returns.
    worker.postMessage({
        demData:   _demData,
        imgW:      _imgW,
        imgH:      _imgH,
        colorData: _colorData,
        colorW:    _colorW,
        colorH:    _colorH,
        MAP_WIDTH, MAP_HEIGHT,
        // Splat density scales with the quality tier — fewer points on
        // low-end / mobile so the cloud stays within memory and fill budget.
        LAND_GRID:  Math.max(1800, Math.round(SPLAT_LAND_GRID  * quality.gridScale())),
        OCEAN_GRID: Math.max(800,  Math.round(SPLAT_OCEAN_GRID * quality.gridScale())),
        VSCALE_LAND:  TERRAIN_VSCALE_LAND,
        VSCALE_OCEAN: TERRAIN_VSCALE_OCEAN,
        prngSeed: 12345,  // fixed seed → deterministic splat distribution
    });

    return splatCloud;
}

export function createSolidOceanFloor(scene) {
    // 512×512 segments — enough resolution to show mid-ocean ridges and trench
    // walls clearly, while keeping the vertex count at 262k (vs 1M at 1024).
    const SEGS   = 512;
    const VERTS  = SEGS + 1;   // vertices per axis
    const geo = new THREE.PlaneGeometry(MAP_WIDTH, MAP_HEIGHT, SEGS, SEGS);
    geo.rotateX(-Math.PI / 2);

    const pos = geo.attributes.position;

    // ── Pass 1: sample GEBCO / Terrarium for every vertex ────────────────────
    const elevations = new Float32Array(pos.count);
    const rawY       = new Float32Array(pos.count);

    for (let i = 0; i < pos.count; i++) {
        const x       = pos.getX(i);
        const z       = pos.getZ(i);
        const hMeters = getBestElevation(x, z);
        elevations[i] = hMeters;

        const dist   = Math.sqrt((x / MAP_WIDTH) ** 2 + (z / MAP_HEIGHT) ** 2);
        const curveY = -Math.pow(dist, 2) * 20.0;
        rawY[i] = (hMeters < 0 ? (hMeters / 900.0) * TERRAIN_VSCALE_OCEAN
                               : (hMeters / 1000.0) * TERRAIN_VSCALE_LAND) + curveY - 0.2;
    }

    // ── Pass 2: 6-iteration Gaussian-weighted smoothing (ocean only) ────────
    // 5-point equal-weight cross wasn't enough for GEBCO's steepest shelf-break
    // walls.  Switching to a 9-point weighted kernel (centre×4, edge×2, corner×1
    // normalised to 16) and running 6 passes eliminates the remaining spires
    // while preserving the broad shape of ridges and trenches.
    const tmpY = new Float32Array(rawY);
    for (let pass = 0; pass < 6; pass++) {
        for (let row = 1; row < VERTS - 1; row++) {
            for (let col = 1; col < VERTS - 1; col++) {
                const i = row * VERTS + col;
                if (elevations[i] >= 0) continue;   // land — leave untouched
                // 3×3 Gaussian weights: centre=4, edges=2, corners=1, sum=16
                const tl = rawY[i - VERTS - 1], tc = rawY[i - VERTS], tr = rawY[i - VERTS + 1];
                const ml = rawY[i - 1],         mc = rawY[i],          mr = rawY[i + 1];
                const bl = rawY[i + VERTS - 1], bc = rawY[i + VERTS],  br = rawY[i + VERTS + 1];
                tmpY[i] = (tl + tr + bl + br
                         + (tc + ml + mr + bc) * 2.0
                         +  mc                 * 4.0) / 16.0;
            }
        }
        rawY.set(tmpY);
    }

    // Apply smoothed heights and build colour / elevation arrays
    const colors = [];

    for (let i = 0; i < pos.count; i++) {
        pos.setY(i, rawY[i]);

        const hMeters = elevations[i];
        if (hMeters < 0) {
            // ── Bathymetric depth-band colouring (tuned for visible bathymetry)
            // Now that the seaPlane + washPlane covers are gone, the ocean
            // floor is fully visible. Depth bands widened — shelves brighter,
            // trenches darker — so depth reads as real contrast instead of
            // needing a flat overlay for figure/ground separation.
            //
            //   Shelf  (   0–  200 m) : lit cyan, brighter than before
            //   Slope  ( 200–2 000 m) : steel blue → continental slope colour
            //   Abyss  (2000–6 000 m) : deep blue-indigo
            //   Hadal  (    > 6000 m) : near-black indigo-violet
            //
            // Endpoints of adjacent bands are kept continuous so the boundary
            // between e.g. shelf and slope reads as a smooth gradient, not a
            // discrete colour break visible at 200 m.
            const d = Math.abs(hMeters);
            let r, g, b;
            if (d < 200) {
                // Shelf — pushed brighter (was 0.58 max blue, now 0.78). Reads
                // as sunlit shallow water against deeper bands below.
                const t = d / 200;
                r = 0.06  - t * 0.030;   // 0.060 → 0.030
                g = 0.32  - t * 0.160;   // 0.320 → 0.160
                b = 0.78  - t * 0.230;   // 0.780 → 0.550
            } else if (d < 2000) {
                // Slope — continental shelf break to abyssal plain transition.
                // Endpoints match shelf (top) and abyss (bottom) for continuity.
                const t = (d - 200) / 1800;
                r = 0.030 - t * 0.015;   // 0.030 → 0.015
                g = 0.160 - t * 0.100;   // 0.160 → 0.060
                b = 0.550 - t * 0.200;   // 0.550 → 0.350
            } else if (d < 6000) {
                // Abyss — deep blue-indigo. Was max blue 0.18, now 0.10 at 6km.
                const t = (d - 2000) / 4000;
                r = 0.015 - t * 0.008;   // 0.015 → 0.007
                g = 0.060 - t * 0.035;   // 0.060 → 0.025
                b = 0.350 - t * 0.180;   // 0.350 → 0.170
            } else {
                // Hadal — Mariana / Tonga / Kuril trenches. Pushed darker than
                // before (0.180→0.100 was the old end; now 0.170→0.055) so
                // trenches read as visibly different from regular abyss.
                const t = Math.min(1.0, (d - 6000) / 4000);
                r = 0.007 - t * 0.003;   // 0.007 → 0.004
                g = 0.025 - t * 0.013;   // 0.025 → 0.012
                b = 0.170 - t * 0.115;   // 0.170 → 0.055
            }
            colors.push(r, g, b);
        } else {
            // Land vertices — placeholder only; discarded in the fragment shader
            // so they never occlude the point cloud above them.
            colors.push(0.0, 0.0, 0.0);
        }
    }

    pos.needsUpdate = true;
    geo.setAttribute('color',          new THREE.Float32BufferAttribute(colors,                3));
    geo.setAttribute('aTrueElevation', new THREE.Float32BufferAttribute(elevations,            1));
    geo.computeVertexNormals();

    const mat = new THREE.MeshStandardMaterial({
        name: 'OceanFloor',
        vertexColors: true, roughness: 0.72, metalness: 0.12, flatShading: false,
        emissive:          new THREE.Color(0x002244),
        emissiveIntensity: 0.70,
        // alphaTest required so the land-discard in onBeforeCompile doesn't
        // leave ghost depth writes that occlude the point cloud behind them.
        alphaTest: 0.01,
    });

    mat.userData = { showContours: { value: 1.0 } };
    mat.onBeforeCompile = (shader) => {
        shader.uniforms.uShowContours = mat.userData.showContours;
        shader.vertexShader = `
            attribute float aTrueElevation;
            varying float vTrueElevation;
            ${shader.vertexShader}
        `.replace(
            `#include <color_vertex>`,
            `#include <color_vertex>\n vTrueElevation = aTrueElevation;`
        );
        shader.fragmentShader = `
            uniform float uShowContours;
            varying float vTrueElevation;
            ${shader.fragmentShader}
        `.replace(
            `#include <clipping_planes_fragment>`,
            `#include <clipping_planes_fragment>
            // Was: discard at vTrueElevation >= -1.0, which left a 1m-tall
            // band of coastal DEM that fell into the gap between the ocean
            // splat (skips hMeters >= 0) and the land splat (sparse at edges).
            // Result: pure-black pixelated holes at coastlines (visible in
            // Norwegian fjords and similar intricate coast lines).
            // Now: discard only at strictly positive elevation. Coastal
            // shallows in the -1m..0m band stay covered by the floor mesh.
            if (vTrueElevation >= 0.0) discard;
            `
        ).replace(
            `#include <dithering_fragment>`,
            `#include <dithering_fragment>

            if (uShowContours > 0.5 && vTrueElevation < -50.0) {
                float absD      = abs(vTrueElevation);
                float width     = fwidth(vTrueElevation);
                if (width > 0.0) {
                    // Minor contour every 500 m — soft teal
                    float minorMod  = mod(absD, 500.0);
                    float minorEdge = min(minorMod, 500.0 - minorMod);
                    float isMinor   = (1.0 - smoothstep(0.0, width * 1.5, minorEdge))
                                      * clamp(absD / 400.0, 0.0, 1.0);
                    // Major contour every 2 500 m — bright cyan
                    float majorMod  = mod(absD, 2500.0);
                    float majorEdge = min(majorMod, 2500.0 - majorMod);
                    float isMajor   = 1.0 - smoothstep(0.0, width * 2.0, majorEdge);

                    vec3  minorCol   = vec3(0.08, 0.42, 0.72);
                    vec3  majorCol   = vec3(0.22, 0.72, 0.95);  // brighter
                    // Minor halved (0.30→0.15) so 500m grid stops dominating
                    // flat abyssal plains; major lifted (0.58→0.72) so the
                    // 2500m landmarks read sharply against quieter background.
                    float finalAlpha = max(isMinor * 0.15, isMajor * 0.72);
                    gl_FragColor.rgb = mix(gl_FragColor.rgb,
                                          mix(minorCol, majorCol, isMajor),
                                          finalAlpha);
                }
            }

            // ── Per-depth emissive accent ─────────────────────────────────────
            if (vTrueElevation < -50.0) {
                float absD = abs(vTrueElevation);
                // Shallow shelf — soft cyan lift (sunlit water)
                float shelfT  = clamp(1.0 - absD / 300.0, 0.0, 1.0);
                gl_FragColor.rgb += vec3(0.010, 0.030, 0.060) * shelfT;
                // Mid-ocean ridge glow — peaks around 2 000–2 500 m
                float ridgeT  = exp(-pow((absD - 2200.0) / 800.0, 2.0)) * 0.35;
                gl_FragColor.rgb += vec3(0.004, 0.018, 0.055) * ridgeT;
                // Hadal darkening > 6 000 m
                float trenchT = clamp((absD - 6000.0) / 3000.0, 0.0, 1.0);
                gl_FragColor.rgb *= 1.0 - trenchT * 0.30;
            }
            `
        );
    };

    const oceanFloorMesh = new THREE.Mesh(geo, mat);
    scene.add(oceanFloorMesh);

    // Aquarium walls REMOVED. They were independent geometry that hid the
    // ocean floor + water plane rectangular edges from oblique camera angles.
    // The map now shows its raw boundaries; the B-vs-C edge treatment is the
    // next decision point. aquariumWalls returned as null to preserve the
    // destructure signature at main.js:193 and uiController.js:628 (both
    // destructure but never read the value, so null is safe).
    return { oceanFloorMesh, aquariumWalls: null };
}

export function createCountryBorders(scene, worldBordersGeoJSON) {
    const bordersGroup = new THREE.Group();
    scene.add(bordersGroup);
    if (!worldBordersGeoJSON || !worldBordersGeoJSON.features) return bordersGroup;

    // Geography tier — dark muted navy, NormalBlending, low opacity.
    // Previously this was 0x40c4ff + AdditiveBlending: the same colour and
    // blend mode as active heading lines, making borders indistinguishable
    // from live data tracks.  Now they sit clearly in the cartographic layer.
    const borderMat = new THREE.LineBasicMaterial({
        color: 0x1e4060, transparent: true, opacity: 0.22,
        blending: THREE.NormalBlending,
    });

    worldBordersGeoJSON.features.forEach(feature => {
        if (!feature.geometry) return;
        const { type, coordinates } = feature.geometry;
        if (type === 'Polygon') {
            coordinates.forEach(ring => _drawBorderRing(ring, borderMat, bordersGroup));
        } else if (type === 'MultiPolygon') {
            coordinates.forEach(poly =>
                poly.forEach(ring => _drawBorderRing(ring, borderMat, bordersGroup))
            );
        }
    });

    return bordersGroup;
}

function _drawBorderRing(ring, material, bordersGroup) {
    let points = [];

    ring.forEach(coord => {
        const lon    = coord[0];
        const lat    = coord[1];
        const x      = (lon / 180.0) * (MAP_WIDTH / 2.0);
        const latRad = lat * (Math.PI / 180.0);
        const mercY  = Math.log(Math.tan((Math.PI / 4.0) + (latRad / 2.0)));
        let   z      = -(mercY / Math.PI) * (MAP_HEIGHT / 2.0);

        z = Math.max(-MAP_HEIGHT / 2, Math.min(MAP_HEIGHT / 2, z));

        const hMeters = getTrueElevation(x, z);
        const isOcean = hMeters < 0;
        const dist    = Math.sqrt((x / MAP_WIDTH) ** 2 + (z / MAP_HEIGHT) ** 2);
        const curveY  = -Math.pow(dist, 2) * 20.0;
        const finalY  = isOcean ? (hMeters / 600.0) * TERRAIN_VSCALE_OCEAN
                                : (hMeters / 1000.0) * TERRAIN_VSCALE_LAND;

        // Break line at anti-meridian jumps
        if (points.length > 0 && Math.abs(x - points[points.length - 1].x) > MAP_WIDTH * 0.5) {
            if (points.length > 1) {
                bordersGroup.add(new THREE.Line(
                    new THREE.BufferGeometry().setFromPoints(points), material
                ));
            }
            points = [];
        }

        points.push(new THREE.Vector3(x, finalY + curveY + 0.4, z));
    });

    if (points.length > 1) {
        bordersGroup.add(new THREE.Line(
            new THREE.BufferGeometry().setFromPoints(points), material
        ));
    }
}

// ── Ocean depth markers ───────────────────────────────────────────────────────
// Named sprites + measurement stems for major trenches, ridges, and ocean basins.
// Style matches the port label system: dark navy pill, teal border, cyan text.
const OCEAN_FEATURES = [
    { name: 'MARIANA TRENCH',      lon:  142.2, lat:  11.35, depthM: 10935 },
    { name: 'TONGA TRENCH',        lon: -174.7, lat: -23.0,  depthM: 10882 },
    { name: 'PHILIPPINE TRENCH',   lon:  126.6, lat:  10.5,  depthM: 10540 },
    { name: 'PUERTO RICO TRENCH',  lon:  -66.5, lat:  19.6,  depthM:  8376 },
    { name: 'S. SANDWICH TRENCH',  lon:  -25.5, lat: -55.5,  depthM:  8266 },
    { name: 'JAVA TRENCH',         lon:  108.0, lat:  -9.0,  depthM:  7725 },
    { name: 'JAPAN TRENCH',        lon:  143.5, lat:  36.0,  depthM:  8412 },
    { name: 'KERMADEC TRENCH',     lon: -177.0, lat: -30.0,  depthM:  9994 },
    { name: 'MID-ATLANTIC RIDGE',  lon:  -25.0, lat:   0.0,  depthM:  2500 },
    { name: 'EAST PACIFIC RISE',   lon: -109.0, lat:  -5.0,  depthM:  2750 },
];

function _makeDepthSprite(name, depthM) {
    const W = 256, H = 72;
    const canvas = document.createElement('canvas');
    canvas.width  = W;
    canvas.height = H;
    const ctx = canvas.getContext('2d');

    // Background pill
    const rx = 6;
    ctx.beginPath();
    ctx.moveTo(rx, 2); ctx.lineTo(W - rx, 2);
    ctx.arcTo(W - 2, 2, W - 2, rx + 2, rx);
    ctx.lineTo(W - 2, H - rx); ctx.arcTo(W - 2, H - 2, W - rx - 2, H - 2, rx);
    ctx.lineTo(rx + 2, H - 2); ctx.arcTo(2, H - 2, 2, H - rx - 2, rx);
    ctx.lineTo(2, rx + 2);     ctx.arcTo(2, 2, rx + 2, 2, rx);
    ctx.closePath();

    const isTrench = depthM > 3000;
    ctx.fillStyle   = isTrench ? 'rgba(0, 4, 14, 0.90)' : 'rgba(0, 8, 20, 0.82)';
    ctx.fill();
    ctx.strokeStyle = isTrench ? 'rgba(64, 196, 255, 0.75)' : 'rgba(0, 200, 160, 0.60)';
    ctx.lineWidth   = 1.5;
    ctx.stroke();

    // Feature name (small, dimmer)
    ctx.textAlign    = 'center';
    ctx.textBaseline = 'alphabetic';
    ctx.font         = 'bold 10px Courier New';
    ctx.fillStyle    = isTrench ? 'rgba(64, 196, 255, 0.70)' : 'rgba(0, 220, 170, 0.70)';
    ctx.fillText(name, W / 2, 24);

    // Depth reading (larger, bright)
    const depthStr = `▼ ${depthM.toLocaleString()} m`;
    ctx.font        = 'bold 18px Courier New';
    ctx.shadowColor = isTrench ? '#40c4ff' : '#00dca0';
    ctx.shadowBlur  = 8;
    ctx.fillStyle   = isTrench ? 'rgba(64, 196, 255, 0.98)' : 'rgba(0, 220, 160, 0.95)';
    ctx.fillText(depthStr, W / 2, 56);
    ctx.shadowBlur  = 0;

    const tex = new THREE.CanvasTexture(canvas);
    const mat = new THREE.SpriteMaterial({ map: tex, transparent: true, depthTest: false, opacity: 0.92 });
    const spr = new THREE.Sprite(mat);
    spr.scale.set(14, 14 * (H / W), 1);
    spr.renderOrder = 990;
    return spr;
}

export function createOceanDepthMarkers(scene) {
    const group = new THREE.Group();
    group.name  = 'oceanDepthMarkers';
    scene.add(group);

    for (const feat of OCEAN_FEATURES) {
        // Scene XZ via Mercator (consistent with lonLatToScene / ship positions)
        const x      = (feat.lon / 180.0) * (MAP_WIDTH / 2.0);
        const latRad = feat.lat * (Math.PI / 180.0);
        const mercY  = Math.log(Math.tan(Math.PI / 4.0 + latRad / 2.0));
        const z      = -(mercY / Math.PI) * (MAP_HEIGHT / 2.0);

        // Ocean floor Y — mirrors createSolidOceanFloor's displacement formula
        const hMeters = getBestElevation(x, z);
        const dist    = Math.sqrt((x / MAP_WIDTH) ** 2 + (z / MAP_HEIGHT) ** 2);
        const curveY  = -Math.pow(dist, 2) * 20.0;
        const floorY  = (hMeters / 800.0) * TERRAIN_VSCALE_OCEAN + curveY - 0.2;

        // Label floats above the floor; stem connects label to floor
        const stemHeight = Math.max(1.5, Math.abs(hMeters) / 800.0 * 0.18);
        const labelY     = floorY + stemHeight + 1.5;

        // Stem line
        const stemGeo = new THREE.BufferGeometry().setFromPoints([
            new THREE.Vector3(x, floorY + 0.1, z),
            new THREE.Vector3(x, labelY - 0.8,  z),
        ]);
        const stemMat = new THREE.LineBasicMaterial({
            color: feat.depthM > 3000 ? 0x40c4ff : 0x00dca0,
            transparent: true, opacity: 0.45, depthTest: false,
        });
        group.add(new THREE.Line(stemGeo, stemMat));

        // Label sprite
        const sprite = _makeDepthSprite(feat.name, feat.depthM);
        sprite.position.set(x, labelY, z);
        group.add(sprite);
    }

    return group;
}

// ── Ocean basin & feature labels ─────────────────────────────────────────────
// Ambient cartographic text floating in the water column — no background boxes,
// pure typography.  Three tiers mirror the hierarchy of a nautical chart:
//   Tier 1 — major ocean basins  (large, soft blue-white, ~50 world units wide)
//   Tier 2 — secondary seas      (medium, cooler blue)
//   Tier 3 — ridge / trench systems (small, muted teal-blue)

const _BASIN_FEATURES = [
    // ── Tier 1: named oceans ──────────────────────────────────────────────────
    { name: 'PACIFIC  OCEAN',    lon: -155.0, lat:   5.0, tier: 1 },
    { name: 'ATLANTIC  OCEAN',   lon:  -30.0, lat:   5.0, tier: 1 },
    { name: 'INDIAN  OCEAN',     lon:   78.0, lat: -22.0, tier: 1 },
    { name: 'SOUTHERN  OCEAN',   lon:    0.0, lat: -57.0, tier: 1 },
    { name: 'ARCTIC  OCEAN',     lon:    0.0, lat:  78.0, tier: 1 },

    // ── Tier 2: secondary seas ────────────────────────────────────────────────
    { name: 'CARIBBEAN SEA',     lon:  -75.0, lat:  16.0, tier: 2 },
    { name: 'MEDITERRANEAN',     lon:   18.0, lat:  36.0, tier: 2 },
    { name: 'SOUTH CHINA SEA',   lon:  114.0, lat:  13.0, tier: 2 },
    { name: 'BERING SEA',        lon: -173.0, lat:  57.0, tier: 2 },
    { name: 'ARABIAN SEA',       lon:   63.0, lat:  15.0, tier: 2 },
    { name: 'BAY OF BENGAL',     lon:   88.0, lat:  12.0, tier: 2 },
    { name: 'CORAL SEA',         lon:  152.0, lat: -17.0, tier: 2 },
    { name: 'TASMAN SEA',        lon:  158.0, lat: -38.0, tier: 2 },
    { name: 'GULF OF MEXICO',    lon:  -90.0, lat:  24.0, tier: 2 },
    { name: 'RED SEA',           lon:   37.0, lat:  21.0, tier: 2 },
    { name: 'NORTH SEA',         lon:    4.0, lat:  57.0, tier: 2 },
    { name: 'SEA OF JAPAN',      lon:  134.0, lat:  40.0, tier: 2 },
    { name: 'PHILIPPINE SEA',    lon:  133.0, lat:  18.0, tier: 2 },

    // ── Tier 3: ridge & trench systems ────────────────────────────────────────
    { name: 'MID-ATLANTIC RIDGE',    lon:  -26.0, lat:   0.0, tier: 3 },
    { name: 'EAST PACIFIC RISE',     lon: -109.0, lat: -15.0, tier: 3 },
    { name: 'SW INDIAN RIDGE',       lon:   42.0, lat: -48.0, tier: 3 },
    { name: 'CENTRAL INDIAN RIDGE',  lon:   68.0, lat: -10.0, tier: 3 },
    { name: 'TONGA-KERMADEC TRENCH', lon: -175.0, lat: -25.0, tier: 3 },
    { name: 'MARIANA TRENCH',        lon:  143.0, lat:  13.0, tier: 3 },
    { name: 'PUERTO RICO TRENCH',    lon:  -65.0, lat:  20.0, tier: 3 },
    { name: 'JAVA TRENCH',           lon:  107.0, lat:  -8.0, tier: 3 },
];

// Canvas colour palette by tier
const _TIER_STYLE = {
    1: { fontSize: 26, canvasW: 960, canvasH: 72, spriteW: 55,
         fill: 'rgba(170, 215, 255, 0.72)', glow: 'rgba(110, 175, 255, 0.55)', blur: 14, opacity: 0.95 },
    2: { fontSize: 17, canvasW: 640, canvasH: 52, spriteW: 34,
         fill: 'rgba(120, 180, 235, 0.62)', glow: 'rgba( 80, 150, 215, 0.42)', blur: 10, opacity: 0.88 },
    3: { fontSize: 13, canvasW: 512, canvasH: 40, spriteW: 24,
         fill: 'rgba( 85, 160, 205, 0.52)', glow: 'rgba( 55, 125, 185, 0.32)', blur:  7, opacity: 0.80 },
};

function _makeBasinSprite(name, tier) {
    const s = _TIER_STYLE[tier];
    const canvas = document.createElement('canvas');
    canvas.width  = s.canvasW;
    canvas.height = s.canvasH;
    const ctx = canvas.getContext('2d');

    ctx.textAlign    = 'center';
    ctx.textBaseline = 'middle';
    ctx.font         = `300 ${s.fontSize}px 'Courier New', monospace`;

    // Wide letter-spacing for the cartographic chart feel
    if ('letterSpacing' in ctx) ctx.letterSpacing = `${Math.round(s.fontSize * 0.55)}px`;

    // Two-pass glow — outer halo then sharp fill
    ctx.shadowColor = s.glow;
    ctx.shadowBlur  = s.blur;
    ctx.fillStyle   = s.fill;
    ctx.fillText(name, s.canvasW / 2, s.canvasH / 2);
    ctx.shadowBlur  = s.blur * 0.4;
    ctx.fillText(name, s.canvasW / 2, s.canvasH / 2);
    ctx.shadowBlur  = 0;

    const tex = new THREE.CanvasTexture(canvas);
    const mat = new THREE.SpriteMaterial({
        map: tex, transparent: true, depthTest: false, opacity: s.opacity,
    });
    const spr = new THREE.Sprite(mat);
    spr.scale.set(s.spriteW, s.spriteW * (s.canvasH / s.canvasW), 1);
    spr.renderOrder = 982;   // below port labels (998) and depth markers (990)
    return spr;
}

// Convert lon/lat → scene XZ using Mercator (matches lonLatToScene in aisManager)
function _lonLatToXZ(lon, lat) {
    const x      = (lon / 180.0) * (MAP_WIDTH  / 2.0);
    const latRad = lat * (Math.PI / 180.0);
    const mercY  = Math.log(Math.tan(Math.PI / 4.0 + latRad / 2.0));
    const z      = -(mercY / Math.PI) * (MAP_HEIGHT / 2.0);
    return { x, z };
}

export function createOceanBasinLabels(scene) {
    const group = new THREE.Group();
    group.name  = 'oceanBasinLabels';
    scene.add(group);

    // Y positions — labels float in the water column, clearly below the surface
    // but above the deep ocean floor so they're readable from oblique angles.
    const tierY = { 1: -1.2, 2: -0.9, 3: -0.6 };

    for (const feat of _BASIN_FEATURES) {
        const { x, z } = _lonLatToXZ(feat.lon, feat.lat);
        // Clamp near-polar labels to map bounds
        if (Math.abs(z) > MAP_HEIGHT * 0.48) continue;

        const sprite = _makeBasinSprite(feat.name, feat.tier);
        sprite.position.set(x, tierY[feat.tier], z);
        group.add(sprite);
    }

    return group;
}

// ── Point cloud crossfade LOD ─────────────────────────────────────────────────
// Call every frame alongside continentMesh.update(camera).
// Point cloud stays fully visible until close zoom, then crossfades with mesh.
//   camera.y > 25  → uFade = 1.0  (point cloud fully visible)
//   camera.y 25→10 → uFade 1→0    (fades as continent mesh fades in)
export function updatePointCloud(camera) {
    if (!_splatCloud) return;
    const fade = THREE.MathUtils.clamp(
        (camera.position.y - SPLAT_FADE_END) / (SPLAT_FADE_START - SPLAT_FADE_END), 0, 1
    );
    _splatCloud.material.uniforms.uFade.value = fade;
    _splatCloud.visible = fade > 0;

    // Compute tilt: dot of camera look direction with world up (0,1,0).
    // When looking straight down: dot ≈ -1 → tilt = 0 (no boost needed).
    // When looking horizontally:  dot ≈  0 → tilt = 1 (full boost applied).
    const lookDir = new THREE.Vector3();
    camera.getWorldDirection(lookDir);
    const tilt = THREE.MathUtils.clamp(1.0 + lookDir.y, 0, 1);
    _splatCloud.material.uniforms.uTilt.value = tilt;
}
